intifil/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    # media and static
    (r'^media/(?P<path>.*)$','django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT,'show_indexes': True}),
    (r'^static/(?P<path>.*)$','django.views.static.serve',
         {'document_root': settings.STATIC_ROOT,'show_indexes': True}),
    # third apps
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # local apps
    url(r'^sitemap/$', include('sitemap.urls')),
    url(r'^global_presence/', include('global_presence.urls')),
    url(r'^teams/', include('teams.urls')),
    url(r'^', include('items.urls')),
)

items/urls.py
# -*- coding: utf-8 -*-
""" items' urls """

from django.conf.urls import patterns, url
from .views import HomeView, HomeCategoryView, ItemDetailView,\
    ItemOrderView


urlpatterns = patterns('items.views',
    url(
        regex=r'^items/reorder_home_items/$',
        view=ItemOrderView.as_view(),
        name='reorder_home_items'
    ),
    url(
        regex=r'^items/get_photos_by_screen/$',
        view='json_get_photos_by_screen',
        name='get_photos_by_screen'
    ),
    url(
        regex=r'^items/get_mini_by_screen/$',
        view='json_get_mini_by_screen',
        name='get_mini_by_screen'
    ),
    url(
        regex=r'^items/get_slider_by_screen/$',
        view='json_get_slider_by_screen',
        name='get_slider_by_screen'
    ),
    url(
        regex=r'^(?P<slug_category>[-_\w]+)/(?P<slug>[-_\w]+)/$',
        view=ItemDetailView.as_view(),
        name="item_detail"
    ),
    url(
        regex=r'^(?P<slug>[-_\w]+)/$',
        view=HomeCategoryView.as_view(),
        name="home"
    ),
    url(
        regex=r'^$',
        view=HomeView.as_view(),
        name="home"
    ),
)

teams/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from teams.views import TeamDetailView

urlpatterns = patterns('teams.views',
    url(
        regex=r'^get_mini_by_screen/$',
        view='json_get_mini_by_screen',
        name='get_teammini_by_screen'
    ),
    url(
        regex=r'^get_photo_by_screen/(?P<slug>[-_\w]+)/$',
        view='json_get_photo_by_screen',
        name='get_teamphoto_by_screen'
    ),
    url(
        regex=r'^get_teammember_photos_by_screen/$',
        view='json_get_teammember_photos_by_screen',
        name='get_teammember_photos_by_screen'
    ),
    url(
        regex=r'^(?P<slug>[-_\w]+)/$',
        view=TeamDetailView.as_view(),
        name="team_detail"
    ),
)

teams/models.py
# -*- coding: utf-8 -*-
""" teams' models """

from django.db import models
from django.core.urlresolvers import reverse

from autoslug.fields import AutoSlugField
from common.utils import highlyRandomName
from easy_thumbnails.fields import ThumbnailerImageField
from items.models import ItemHomeManager
from tinymce.models import HTMLField


class Item(models.Model):
    """ Stores information of each item on this application """
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name', unique=True,
                         max_length=255, always_update=True)
    category = models.ForeignKey('items.Category',
                                 related_name='teams_item_set',
                                 blank=True, null=True)
    home_photo = models.OneToOneField('items.HomePhoto', null=True, blank=True,
                                      related_name='teams_item_set')
    show_sub_pages_on_sitemap = models.BooleanField(default=False)
    order = models.SmallIntegerField(default=0)

    # managers
    objects = models.Manager()
    home_objects = ItemHomeManager()

    class Meta:
        ordering = ("order",)
        get_latest_by = ("order",)

    def __unicode__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        """  """
        team_set = self.team_set.all()
        if team_set:
            return team_set[0].get_absolute_url()
        return reverse('home')

    def get_thumbnail_by_screen(self, screen):
        """
        Devuelve el thumbnail según la resolución y al forma de la foto
        """
        return self.home_photo.image[
            "{screen}_{shape}".format(screen=screen,
                                      shape=self.home_photo.get_shape_display())
        ].url

    def get_mini_by_screen(self, screen):
        """
        Devuelve el thumbnail según la resolución y al forma de la foto para la
        galería
        Si tiene algun team (solo deberia existir 1) retorna su thumbnail
        sino retorna el thumbnail del item
        """
        team = self.team_set.latest('id')
        if team:
            thumb = team.get_mini_by_screen(screen)
        else:
            thumb = self.home_photo.image[
                "mini_{screen}".format(screen=screen)].url
        return thumb

    @property
    def get_sub_pages(self):
        """ returns the subpages of this item """
        return self.team_set.all()


class Team(models.Model):
    """
    Equipo de trabajo
    """
    def get_photo_path(self, filename):
        return u'photos/%s' % highlyRandomName(filename)

    name = models.CharField(max_length=200)
    description = HTMLField(blank=True)
    mini_photo = ThumbnailerImageField(upload_to=get_photo_path, null=True)
    photo = ThumbnailerImageField(upload_to=get_photo_path, null=True)
    slug = AutoSlugField(populate_from='name', unique=True,
                         max_length=255, always_update=True)
    order = models.IntegerField(default=0)
    item = models.ForeignKey(Item)

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return u"{obj.name}".format(obj=self)

    def get_absolute_url(self):
        return reverse('team_detail', args=[self.slug])

    def get_mini_by_screen(self, screen):
        """
        Devuelve el thumbnail según la resolución y al forma de la foto para la
        galería
        """
        return self.mini_photo["mini_{screen}".format(screen=screen)].url

    def get_photo_by_screen(self, screen):
        """
        Devuelve la foto según la resolución y al forma de la foto para la
        galería
        """
        return self.photo[
            "teams_team_photo_{screen}".format(screen=screen)].url


class TeamMember(models.Model):
    """
    Miembro del equipo
    """
    def get_photo_path(self, filename):
        return u'photos/%s' % highlyRandomName(filename)

    name = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    photo = ThumbnailerImageField(upload_to=get_photo_path, null=True)
    team = models.ForeignKey(Team)

    def __unicode__(self):
        return u"{obj.name}".format(obj=self)

    class Meta:
        verbose_name = "team member"
        verbose_name_plural = "team members"
        ordering = ['id']

    def get_photo_by_screen(self, screen, position):
        """ Devuelve la foto según la resolución """
        return self.photo[
            "teams_teammember_photo_{position}_{screen}".format(
                position=position, screen=screen)].url

teams/views.py
# -*- coding: utf-8 -*-
""" teams' views """

from django.views.generic import DetailView

from common.utils import json_response
from teams.models import Team, TeamMember


class TeamDetailView(DetailView):
    """
    Galería de un item
    """
    model = Team
    template_name = "teams/team_detail.html"


def json_get_mini_by_screen(request):
    """
    :return: devuelve las fotos de los items según la resolución para las
    miniaturas de la galería
    """
    team = Team.objects.latest('id')
    if team:
        queryset = team.item.category.all_item_set
    else:
        queryset = []
    screen = request.GET["screen"]
    data = [{"name": item.name,
             "thumb": item.get_mini_by_screen(screen),
             "slug": item.slug,
             "url": item.get_absolute_url()} for item in queryset]

    return json_response(data)


def json_get_photo_by_screen(request, slug):
    """
    devuelve las foto del equipo según la resolución
    """
    screen = request.GET["screen"]
    item = Team.objects.get(slug=slug)
    data = {"name": item.name, "thumb": item.get_photo_by_screen(screen)}

    return json_response(data)


def json_get_teammember_photos_by_screen(request):
    """
    returns the teammember photos based on the resolution
    """
    screen = request.GET["screen"]
    data = []
    for pos, item in enumerate(TeamMember.objects.all()):
        data.append({"thumb": item.get_photo_by_screen(screen, pos)})

    return json_response(data)

teams/templates/teams/team_detail.html
{% extends "common/base.html" %}

{% load compress thumbnail items_tags %}

{% block title %}Team: {{ object }}{% endblock title %}

{% block extra_js %}
    {% compress js %}
        <script src="{{ STATIC_URL }}teams/js/team_detail.js" type="text/javascript"></script>
        <script type="text/javascript">
            var URL_GET_MINI = "{% url 'get_teammini_by_screen' %}";
	    var URL_GET_PHOTO = "{% url 'get_teamphoto_by_screen' object.slug %}";
	    var ITEM_SLUG = "{{ object.item.slug }}";
	    var URL_GET_TEAMMEMBERS_PHOTO = "{% url 'get_teammember_photos_by_screen' %}"
        </script>
    {% endcompress %}
{% endblock extra_js %}

{% block nav %}{% endblock %}

{% block menu %}{% endblock %}

{% block content %}
    <div id="team_first_block" class="team_block">

        {% include 'common/left_menu/slides_menu.html' %}

	{% include 'common/slide_logo.html' %}

        <div class="team_preview_container"></div> <!-- END TEAM PREVIEW CONTAINER -->

        <div class="team_big_image_container">
            <img src="" alt="">
        </div> <!-- END TEAM BIG IMAGE CONTAINER -->

        <div class="team_description">
            <div class="descripcion_container">
                <h4 class="exact_container">{{ object.name }}</h4>
                <div class="small_text">
                    {{ object.description|safe }}
                </div>
                <div class="next_page">
                    <div class="recuadro">
                        Peru<br>
                        Textile Heritage
                    </div>
                </div>

            </div>
        </div><!-- END TEAM DESCRIPCION -->

        <div class="team_info">
            <h1>INTIFIL SA</h1>
            Neuhofstrasse 8 <br class="br_global_presence_info">
            8834 Schindellegi <br class="br_global_presence_info">
            Switzerland <br>
            Tel +41 44 787 70 00 <br>
              <span class="span_global_presence_info">
            Fax +41 44 787 70 04 <br>
              </span>
            info@intifil.com <br class="br_global_presence_info">
            www.intifil.com
        </div> <!-- END TEAM INFO -->
    </div><!-- END TEAM FIRST BLOCK -->

    <div id="team_second_block" class="team_block">

        {% include 'common/left_menu/slides_menu.html' %}

	{% include 'common/slide_logo.html' %}

        {% with object.teammember_set.all as members %}
	  {% if members.0 %}
            <div class="teammate first">
                <img id="tm_0" alt="{{ members.0.name }}">
		{% comment %}
                <img src="{% thumbnail members.0.photo "200x280" crop upscale %}" alt="{{ members.0.name }}">
		{% endcomment %}
            </div>

            <div class="teammate description first_elem">
              <div class="name text-right">{{ members.0.name }}</div>
              {{ members.0.description }}
            </div>
	  {% endif %}

	  {% if members.1 %}
            <div class="teammate second">
                <img id="tm_1" src="{% thumbnail members.1.photo "200x360" crop upscale %}" alt="{{ members.1.name }}">
            </div>

            <div class="teammate description second_elem">
              <div class="name">{{ members.1.name }}</div>
              {{ members.1.description }}
            </div>
	  {% endif %}

	  {% if members.2 %}
            <div class="teammate third">
                <img id="tm_2" src="{% thumbnail members.2.photo "200x280" crop upscale %}" alt="{{ members.2.name }}">
            </div>

            <div class="teammate description third_elem">
              <div class="name">{{ members.2.name }}</div>
              {{ members.2.description }}
            </div>
	  {% endif %}

	  {% if members.3 %}
            <div class="teammate fourth">
                <img id="tm_3" src="{% thumbnail members.3.photo "360x200" crop upscale %}" alt="{{ members.3.name }}">
            </div>

            <div class="teammate description fourth_elem">
              <div class="name text-right">{{ members.3.name }}</div>
              {{ members.3.description }}
            </div>
	  {% endif %}

	  {% if members.4 %}
            <div class="teammate fifth">
                <img id="tm_4" src="{% thumbnail members.4.photo "200x360" crop upscale %}" alt="{{ members.4.name }}">
            </div>

            <div class="teammate description fifth_elem">
              <div class="name text-right">{{ members.4.name }}</div>
              {{ members.4.description }}
            </div>
	  {% endif %}

	  {% if members.5 %}
            <div class="teammate sixth">
                <img id="tm_5" src="{% thumbnail members.5.photo "466x200" crop upscale %}" alt="{{ members.5.name }}">
            </div>

            <div class="teammate description sixth_elem">
              <div class="name text-right">{{ members.5.name }}</div>
              {{ members.5.description }}
            </div>
	  {% endif %}

        {% endwith %}
    </div><!-- END TEAM SECOND BLOCK -->
{% endblock content %}